### ISSUE TITLE
Evaluation Data

### ISSUE THREAD

**Issue by LeoSarog** [JunhoJeon/depth_refine_reconstruct#1]
Hello,
is it possible to have access to the data that you used for the evaluation? It would be helpful to have the raw depth maps and the clean depth maps from the reconstruction model.
Thanks

**Comment by qzhou711** [comment]
Thanks for your fantastic work in pairwise depth dataset for depth image enhancement using CNN.  It will contribute the next works in depth image completion.

As for a fast implementation, it will be great if you can share the clean depth dataset using in your paper. It will also help to  establish a baseline for next work.
